### ISSUE TITLE
Incorrect usage error thrown when trying to setup a dedicated clair server

### ISSUE THREAD

**Issue by ye** [arminc/clair-scanner#47]
I can't seem to be able to get clair-scanner to work with a dedicated clair server in a separate pod within the same kubernetes cluster. I've tried `-c / --clair `. None of them work. Using `--ip` can get it to at least acknowledged the server but its print out is referencing 127.0.0.1 localloop back address. Does clair-scanner only work with localhost?

Also, `clair-scanner` should have a debug logging verbose option `-v` which it hasn't had yet.

See steps below.

```bash
root@gitlab-runner-2668289193-7skhk:/# ./clair-scanner -v -c "http://clair:6060" 76d05ed08bb4
Error: incorrect usage

Usage: clair-scanner [OPTIONS] IMAGE

Scan local Docker images for vulnerabilities with Clair

Arguments:
  IMAGE=""     Name of the Docker image to scan

Options:
  -w, --whitelist=""                    Path to the whitelist file
  -t, --threshold="Unknown"             CVE severity threshold. Valid values; 'Defcon1', 'Critical', 'High', 'Medium', 'Low', 'Negligible', 'Unknown'
  -c, --clair="http://127.0.0.1:6060"   Clair URL
  --ip="localhost"                      IP address where clair-scanner is running on
  -l, --log=""                          Log to a file
  --all, --reportAll=true               Display all vulnerabilities, even if they are approved
  -r, --report=""                       Report output file, as JSON
root@gitlab-runner-2668289193-7skhk:/# ping clair
PING clair.default.svc.cluster.local (10.3.244.231) 56(84) bytes of data.
^C
--- clair.default.svc.cluster.local ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 999ms

root@gitlab-runner-2668289193-7skhk:/# ./clair-scanner --ip="10.3.244.231" 76d05ed08bb4
2018/06/08 16:17:45 [INFO] ▶ Start clair-scanner
2018/06/08 16:17:52 [INFO] ▶ Server listening on port 9279
2018/06/08 16:17:52 [INFO] ▶ Analyzing c212ed5a00ac395a0b508281c9692bee405948ace8c85c0f8f3feef71f9f7418
2018/06/08 16:17:52 [CRIT] ▶ Could not analyze layer: POST to Clair failed Post http://127.0.0.1:6060/v1/layers: dial tcp 127.0.0.1:6060: getsockopt: connection refused
```

**Comment by arminc** [comment]
clair-scanner works fine with dedicated Clair, you need to know that Clair needs to connect to clair-scanner to fetch the image. 
When you run clair-scanner and you provide the -c option it means you are telling clair-scanner where to find Clair so it can submit a request for a scan. When clair-scanner sends this request it also includes the IP adres where Clair can connect back to, to fetch the image. 
When you use a dedicated Clair like you do you need to specify the --ip option so clair-scanner can tell Clair on which IP Clair can connect to clair-scanner to fetch the image. Otherwise Clair will try to connect to localhost or some internal IP which will newer work because Clair probably can't reach clair-scanner there.

**Comment by ye** [comment]
@arminc thanks for the explanation! So in my case I will need to use both `-c` to specify the dedicated Clair service URL and also the IP address where `clair-scanner` is running on correct? I am pretty sure two pods can talk to each other.

**Comment by usr42** [comment]
@ye Two container talking to each other is definitively possible. I have the exact same setup in my repo https://github.com/usr42/clair-container-scan.
This uses @arminc's containers and tools to scan all locally running containers or one particular docker image with clair.
The goal of my repo is to wire up everything, so that you can scan you images with just one command, as long as you have docker and docker-compose installed.

**Comment by ye** [comment]
@arminc Thank you. Confirmed that I need to specify both clair url with `-c` and self's IP with `--ip`. It's working now perfectly, [see also GitHub notes](https://docs.gitlab.com/ee/ci/examples/container_scanning.html). 

Two suggestions for improvements:
 1. Have a single letter param for `--ip` (in addition to have `--ip`) since it's a required param for dedicated clair host setup, that is, clair-scanner not running on the same host as clair. This is to keep it consistent with all other parameters, which almost all have a single letter equivalent.
 1. Fix the typo in the guide in the whitelist section below, I think you meant "Approve"
![screen shot 2018-06-12 at 12 09 08 pm](https://user-images.githubusercontent.com/133924/41302815-7d55dff2-6e39-11e8-80de-c12f2558adad.png)

Having said that, I am closing this ticket as my problem is consider resolved.
